name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.8
  - cudnn=8.9
  - cupti=11.8
  - mpi4py=3.1   # installs cuda-aware openmpi
  - nccl=2.18
  - pip=23.2
  - python=3.11
  - tensorflow-gpu=2.12  # installs tensorflow=2.12 with gpu support